[package]
name = "hyper-reverse-proxy"
version = "0.4.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>", "Felipe Noronha <felipenoris@gmail.com>"]
license = "Apache-2.0"
description = "A simple reverse proxy, to be used with Hyper and Tokio."
homepage = "https://github.com/felipenoris/hyper-reverse-proxy"
documentation = "https://docs.rs/hyper-reverse-proxy"
repository = "https://github.com/felipenoris/hyper-reverse-proxy"
keywords = ["http", "hyper"]
categories = ["network-programming", "web-programming"]
readme = "README.md"
edition = "2018"

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*"
]

[dependencies]
hyper = "0.12"
futures = "0.1"
lazy_static = "1.3"
unicase = "2.3"
hyper-tls = { version = "0.3.2", optional = true }

[features]
https = ["hyper-tls"]
